<!--
// From: C:\Src\sysdocs\generate\adrApps.py on 2025-05-19 21:12:01.764593
var applu = '2025-05-19 21:12:02.404508';
var androidApps = [ 'VIP Access',
                    'Screen Off and Lock',
                    'T-Life',
                    'Android System Update',
                    'Phonograph',
                    'TouchTunes',
                    'Zoom',
                    'Lyft',
                    'Extra Space',
                    'Instagram',
                    'PDF Reader',
                    'COPC MyChart',
                    'MyChart',
                    'Atomic Clock & Watch Accuracy Tool',
                    'Visual Voicemail',
                    'Android System Key Verifier',
                    'Silent Mode Widget',
                    'Compass',
                    'T-Mobile App Experience',
                    'Allstate Motor Club',
                    'Uber',
                    'Facebook',
                    'QR Scanner',
                    'Messenger',
                    'Firefox',
                    'MyRecorder',
                    'Data Transfer Tool',
                    'Termux',
                    'Android System SafetyCore',
                    'Simplenote',
                    'AccuWeather',
                    'Sunrise Free',
                    'Okta Verify',
                    'AppHub',
                    'Mobile Security',
                    'F-Stop',
                    'Authenticator',
                    'Scam Shield',
                    'OHGO',
                    'Backgammon Gold',
                    'WiFi File Transfer' ];
//-->
